sudo: false
language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - spatialite-bin
    - python-pysqlite2
notifications:
  email: false
install:
  - deactivate
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
